apiVersion: automation.cloudbees.io/v1alpha1
name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build - JDK ${{ matrix.java }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: cb-actions/checkout@v2
      - name: Get Date
 
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          
      - name: Build Quarkus main
        if: ${{ github.base_ref == 'development' }}
        run: |
          git clone https://github.com/quarkusio/quarkus.git
          cd quarkus
          ./mvnw -T1C -e -B --settings .github/mvn-settings.xml clean install -Dquickly-ci
          
      - name: Build with Maven
        run: export LANG=en_US && ./mvnw -e -B -fae --settings .github/mvn-settings.xml clean install -Dstart-containers

      
