apiVersion: automation.cloudbees.io/v1alpha1
name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build Java
    runs-on: ubuntu-latest
    
    steps:
      - uses: cb-actions/checkout@v2
      - name: Checkout

      - name: Build with Maven
        run: export LANG=en_US && ./mvnw -e -B -fae --settings .github/mvn-settings.xml clean install -Dstart-containers

      
