apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Quarkus pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
    
      - name: Maven build
        uses: docker://maven:3-eclipse-temurin-17
        shell: sh
        run: |
          echo "bulding Quarkus tutorial"
          mvn io.quarkus.platform:quarkus-maven-plugin:3.3.1:create \
            -DprojectGroupId=org.acme \
            -DprojectArtifactId=getting-started \
            -Dextensions='resteasy-reactive'
          echo "build complete"