apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Quarkus pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
    
      - name: Maven build
        uses: docker://maven:3-eclipse-temurin-17
        shell: sh
        run: |
          echo "bulding Quarkus tutorial"
          mvn "io.quarkus.platform:quarkus-maven-plugin:create" -DprojectGroupId="com.redhat.developers" -DprojectArtifactId="tutorial-app" -DprojectVersion="1.0-SNAPSHOT" -Dextensions=resteasy-reactive

